name: Adding docker image to the Docker hub

on: push

jobs: 
  DockerImage:
    runs-on: Ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@3

      - name: Cache dependencies
        uses: actions/cache@v4
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
     
      - name: Install dependencies
        run: npm Install
      
      - name: Run tests
        run: npm test